// auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_START = 'LOGIN_START';

// redflags
export const GET_RED_FLAGS = 'GET_RED_FLAGS';

// interventions
export const GET_INTERVENTIONS = 'GET_INTERVENTIONS';

// incidents
export const POST_INCIDENT_START = 'POST_INCIDENT_START';
export const POST_INCIDENT_SUCCESS = 'POST_INCIDENT_SUCCESS';
export const POST_INCIDENT_FAILURE = 'POST_INCIDENT_FAILURE';
export const RESET_IS_INCIDENT_POSTED = 'RESET_IS_INCIDENT_POSTED';

export const DELETE_INCIDENT_START = 'DELETE_INCIDENT_START';
export const DELETE_INCIDENT_SUCCESS = 'DELETE_INCIDENT_SUCCESS';
export const DELETE_INCIDENT_FAILURE = 'DELETE_INCIDENT_FAILURE';
export const RESET_IS_INCIDENT_DELETED = 'RESET_IS_INCIDENT_DELETED';

export const GET_INCIDENT_TOTALS = 'GET_INCIDENT_TOTALS';
